apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        # 从日志中提取 trace ID（如果使用了分布式追踪）
        - matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
